version: '3.4'
services:
    romantic_goodall: 
      image: palash315/nodejspractical
      build:
        context: .
        dockerfile: Dockerfile
      restart: unless-stopped
      ports:
      - "8001:80"
      networks:
      - myNetwork
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8001/"]
        interval: 30s
        timeout: 10s
        retries: 3
    restart: on-failure

      
    dazzling_nash:
      image: palash315/task5.1p
      build:
        context: .
        dockerfile: Dockerfile
      restart: unless-stopped
      ports:
      - "3000:3000"
      networks:
      - myNetwork
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:3000/"]
        interval: 30s
        timeout: 10s
        retries: 3
    restart: on-failure
    
    networks:
      myNetwork:
        driver: custom-driver-1
  

